import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className='text-3x-1 mb-4 font-bold text-white'>ETH</p>
        <button
          onClick={() => {}}
          className="font-bold mt-4 bg-purple-500 text-white rounded p-4 shadow-lg">
          Mint NFT
        </button>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
